[versions]
agp = "8.7.0"
kotlin = "1.9.24"
material = "1.12.0"
appcompat = "1.7.0"
coreKtx = "1.13.1"
androidxNavigation = "2.8.3"
flexbox = "3.0.0"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-navigation-navigation-fragment-ktx3 = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
